CREATE TABLE [stat].[StatisticsSummary] (
    [SourceID]          TINYINT          NOT NULL,
    [AggregationID]     TINYINT          NOT NULL,
    [MeasurementID]     TINYINT          NOT NULL,
    [RatingID]          SMALLINT         NOT NULL,
    [TimeControlID]     TINYINT          NOT NULL,
    [ColorID]           TINYINT          NOT NULL,
    [EvaluationGroupID] TINYINT          NOT NULL,
    [CalculationDate]   DATETIME         CONSTRAINT [DF_StatisticsSummary_CalculationDate] DEFAULT (getdate()) NOT NULL,
    [RecordCount]       INT              NULL,
    [Average]           DECIMAL (18, 15) NULL,
    [StandardDeviation] DECIMAL (18, 15) NULL,
    [MinValue]          DECIMAL (18, 15) NULL,
    [LowerPcnt]         DECIMAL (18, 15) NULL,
    [LowerQuartile]     DECIMAL (18, 15) NULL,
    [Median]            DECIMAL (18, 15) NULL,
    [UpperQuartile]     DECIMAL (18, 15) NULL,
    [UpperPcnt]         DECIMAL (18, 15) NULL,
    [MaxValue]          DECIMAL (18, 15) NULL,
    CONSTRAINT [PK_StatisticsSummary] PRIMARY KEY CLUSTERED ([SourceID] ASC, [AggregationID] ASC, [MeasurementID] ASC, [RatingID] ASC, [TimeControlID] ASC, [ColorID] ASC, [EvaluationGroupID] ASC),
    CONSTRAINT [FK_StatisticsSummary_AggregationID] FOREIGN KEY ([AggregationID]) REFERENCES [dim].[Aggregations] ([AggregationID]),
    CONSTRAINT [FK_StatisticsSummary_ColorID] FOREIGN KEY ([ColorID]) REFERENCES [dim].[Colors] ([ColorID]),
    CONSTRAINT [FK_StatisticsSummary_EvaluationGroupID] FOREIGN KEY ([EvaluationGroupID]) REFERENCES [dim].[EvaluationGroups] ([EvaluationGroupID]),
    CONSTRAINT [FK_StatisticsSummary_MeasurementID] FOREIGN KEY ([MeasurementID]) REFERENCES [dim].[Measurements] ([MeasurementID]),
    CONSTRAINT [FK_StatisticsSummary_RatingID] FOREIGN KEY ([RatingID]) REFERENCES [dim].[Ratings] ([RatingID]),
    CONSTRAINT [FK_StatisticsSummary_SourceID] FOREIGN KEY ([SourceID]) REFERENCES [dim].[Sources] ([SourceID]),
    CONSTRAINT [FK_StatisticsSummary_TimeControlID] FOREIGN KEY ([TimeControlID]) REFERENCES [dim].[TimeControls] ([TimeControlID])
);

