CREATE TABLE [lake].[Moves] (
	[GameID] INT NOT NULL
	,[MoveNumber] SMALLINT NOT NULL
	,[ColorID] TINYINT NOT NULL
	,[IsTheory] BIT NULL
	,[IsTablebase] BIT NULL
	,[EngineID] TINYINT NULL
	,[Depth] TINYINT NULL
	,[Clock] INT NULL
	,[TimeSpent] INT NULL
	,[FEN] VARCHAR(92) NOT NULL
	,[PhaseID] TINYINT NOT NULL
	,[Move] VARCHAR(10) NOT NULL
	,[Move_Eval] VARCHAR(7) NULL
	,[T1] VARCHAR(10) NULL
	,[T1_Eval] VARCHAR(7) NULL
	,[T2] VARCHAR(10) NULL
	,[T2_Eval] VARCHAR(7) NULL
	,[T3] VARCHAR(10) NULL
	,[T3_Eval] VARCHAR(7) NULL
	,[T4] VARCHAR(10) NULL
	,[T4_Eval] VARCHAR(7) NULL
	,[T5] VARCHAR(10) NULL
	,[T5_Eval] VARCHAR(7) NULL
	,[T6] VARCHAR(10) NULL
	,[T6_Eval] VARCHAR(7) NULL
	,[T7] VARCHAR(10) NULL
	,[T7_Eval] VARCHAR(7) NULL
	,[T8] VARCHAR(10) NULL
	,[T8_Eval] VARCHAR(7) NULL
	,[T9] VARCHAR(10) NULL
	,[T9_Eval] VARCHAR(7) NULL
	,[T10] VARCHAR(10) NULL
	,[T10_Eval] VARCHAR(7) NULL
	,[Move_Rank] TINYINT NULL
	,[CP_Loss] DECIMAL(5,2) NULL
	,[ScACPL] AS (CASE WHEN [CP_Loss] IS NULL OR LEFT([T1_Eval], 1) = '#' THEN NULL ELSE CONVERT(DECIMAL(5,2), [CP_Loss])/(1 + ABS(CONVERT(DECIMAL(5,2), [T1_Eval]))) END) PERSISTED
	,[MoveScored] BIT CONSTRAINT [DF_LMoves_MoveScored] DEFAULT (0) NOT NULL
	,[TraceKey] CHAR(1) COLLATE Latin1_General_CS_AS NULL  --this needs to be case-sensitive!
	,[MovesAnalyzed] TINYINT NULL
	,[Move_Eval_POV] AS (CASE WHEN [Move_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [Move_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,[T1_Eval_POV] AS (CASE WHEN [T1_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [T1_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,[T2_Eval_POV] AS (CASE WHEN [T2_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [T2_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,[T3_Eval_POV] AS (CASE WHEN [T3_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [T3_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,[T4_Eval_POV] AS (CASE WHEN [T4_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [T4_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,[T5_Eval_POV] AS (CASE WHEN [T5_Eval] LIKE '#%' THEN NULL ELSE CAST(CONVERT(DECIMAL(5,2), [T5_Eval])*ISNULL(NULLIF(CONVERT(SMALLINT, [ColorID]), 2), -1) AS DECIMAL(5,2)) END) PERSISTED
	,CONSTRAINT [PK_LMoves] PRIMARY KEY CLUSTERED ([GameID] ASC, [MoveNumber] ASC, [ColorID] ASC)
	,CONSTRAINT [FK_LMoves_ColorID] FOREIGN KEY ([ColorID]) REFERENCES [dim].[Colors] ([ColorID])
	,CONSTRAINT [FK_LMoves_EngineID] FOREIGN KEY ([EngineID]) REFERENCES [dim].[Engines] ([EngineID])
	,CONSTRAINT [FK_LMoves_GameID] FOREIGN KEY ([GameID]) REFERENCES [lake].[Games] ([GameID]) ON DELETE CASCADE
	,CONSTRAINT [FK_LMoves_PhaseID] FOREIGN KEY ([PhaseID]) REFERENCES [dim].[Phases] ([PhaseID])
	,CONSTRAINT [FK_LMoves_Traces] FOREIGN KEY ([TraceKey]) REFERENCES [dim].[Traces] ([TraceKey])
);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_ColorID] ON [lake].[Moves]([ColorID] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_CPLoss] ON [lake].[Moves]([CP_Loss] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_EngineID] ON [lake].[Moves]([EngineID] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_Evals] ON [lake].[Moves]([MoveScored]) INCLUDE ([T1_Eval_POV], [T2_Eval_POV], [T3_Eval_POV], [T4_Eval_POV], [T5_Eval_POV]);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_T1MoveEvals] ON [lake].[Moves] ([MoveScored]) INCLUDE ([T1_Eval_POV], [Move_Eval_POV]);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_GameID] ON [lake].[Moves]([GameID] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_IsTT] ON [lake].[Moves]([IsTheory] ASC, [IsTablebase] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_PhaseID] ON [lake].[Moves]([PhaseID] ASC);

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_MoveScored] ON [lake].[Moves] (GameID, MoveNumber, ColorID) WHERE MoveScored = 1;

GO
CREATE NONCLUSTERED INDEX [IDX_LMoves_TraceKey] ON [lake].[Moves]([TraceKey] ASC);

GO
CREATE TRIGGER [lake].trg_InsertMoveScores ON lake.Moves

AFTER INSERT

AS

BEGIN
	INSERT INTO stat.MoveScores (
		ScoreID
		,GameID
		,MoveNumber
		,ColorID
	)

	SELECT
		sc.ScoreID
		,i.GameID
		,i.MoveNumber
		,i.ColorID

	FROM inserted AS i
	CROSS JOIN dim.Scores AS sc

	WHERE sc.ScoreActive = 1
END
