CREATE TABLE [rpt].[GameSummary]
(
	GameID INT
	,SourceName VARCHAR(15)
	,SelfWhiteFlag BIT
	,SelfFlagBlack BIT
	,SiteName VARCHAR(26)
	,SiteGameID VARCHAR(15)
	,WhiteLast VARCHAR(50)
	,WhiteFirst VARCHAR(30)
	,WhiteElo SMALLINT
	,BlackLast VARCHAR(50)
	,BlackFirst VARCHAR(30)
	,BlackElo SMALLINT
	,ECO CHAR(3)
	,GameDate DATE
	,EventName VARCHAR(100)
	,RoundNum TINYINT
	,TimeControlDetail VARCHAR(15)
	,TimeControlName VARCHAR(15)
	,Result DECIMAL(2,1)
	,Moves SMALLINT
	,Book_Moves SMALLINT
	,Tablebase_Moves SMALLINT
	,White_CPL_Moves SMALLINT
	,White_CPL_1 SMALLINT
	,White_CPL_2 SMALLINT
	,White_CPL_3 SMALLINT
	,White_CPL_4 SMALLINT
	,White_CPL_5 SMALLINT
	,White_CPL_6 SMALLINT
	,White_CPL_7 SMALLINT
	,White_CPL_8 SMALLINT
	,Black_CPL_Moves SMALLINT
	,Black_CPL_1 SMALLINT
	,Black_CPL_2 SMALLINT
	,Black_CPL_3 SMALLINT
	,Black_CPL_4 SMALLINT
	,Black_CPL_5 SMALLINT
	,Black_CPL_6 SMALLINT
	,Black_CPL_7 SMALLINT
	,Black_CPL_8 SMALLINT
	,White_MovesAnalyzed SMALLINT
	,White_T1 DECIMAL(9,8)
	,White_T2 DECIMAL(9,8)
	,White_T3 DECIMAL(9,8)
	,White_T4 DECIMAL(9,8)
	,White_T5 DECIMAL(9,8)
	,Black_MovesAnalyzed SMALLINT
	,Black_T1 DECIMAL(9,8)
	,Black_T2 DECIMAL(9,8)
	,Black_T3 DECIMAL(9,8)
	,Black_T4 DECIMAL(9,8)
	,Black_T5 DECIMAL(9,8)
	,White_ACPL DECIMAL(9,6)
	,Black_ACPL DECIMAL(9,6)
	,White_SDCPL DECIMAL(9,6)
	,Black_SDCPL DECIMAL(9,6)
	,White_Score DECIMAL(7,4)
	,Black_Score DECIMAL(7,4)
	,White_ROI DECIMAL(9,6)
	,Black_ROI DECIMAL(9,6)
)
GO
