CREATE TABLE [rpt].[OpponentSummary]
(
	SourceName VARCHAR(15) NOT NULL
	,Opp_Color VARCHAR(5) NOT NULL
	,Opp_LastName VARCHAR(50) NOT NULL
	,Opp_FirstName VARCHAR(30) NULL
	,Wins INT NULL
	,Losses INT NULL
	,Draws INT NULL
	,TotalGames INT NULL
	,Score DECIMAL(9,8) NULL
	,Me_MovesAnalyzed INT NULL
	,Opp_MovesAnalyzed INT NULL
	,Me_ACPL DECIMAL(9,6) NULL
	,Opp_ACPL DECIMAL(9,6) NULL
	,Me_SDCPL DECIMAL(9,6) NULL
	,Opp_SDCPL DECIMAL(9,6) NULL
	,Me_Score DECIMAL(7,4) NULL
	,Opp_Score DECIMAL(7,4) NULL
)
