CREATE TABLE [rpt].[YearlyTStatistics]
(
	SourceName VARCHAR(15) NOT NULL
	,MyColor VARCHAR(5) NOT NULL
	,Year INT NOT NULL
	,Games INT NULL
	,Me_MovesAnalyzed INT NULL
	,Me_T1 DECIMAL(9,8) NULL
	,Me_T2 DECIMAL(9,8) NULL
	,Me_T3 DECIMAL(9,8) NULL
	,Me_T4 DECIMAL(9,8) NULL
	,Me_T5 DECIMAL(9,8) NULL
	,Opp_MovesAnalyzed INT NULL
	,Opp_T1 DECIMAL(9,8) NULL
	,Opp_T2 DECIMAL(9,8) NULL
	,Opp_T3 DECIMAL(9,8) NULL
	,Opp_T4 DECIMAL(9,8) NULL
	,Opp_T5 DECIMAL(9,8) NULL
)
